export type HiLoRound = {
  game?: 'hilo';
  id: string;
  amount: number;
  payout: number;
  won: boolean;
  result: number;
  threshold: number;
  direction: string;
  clientSeed: string;
  nonce: number;
  commitment: string;
  rtpBps: number;
  multiplier: number;
  createdAt: string;
};
export type LadderRound = {
  game: 'ladder';
  protocol: 'stairs-v1';
  id: string;
  amount: number;
  rocks: number;
  clientSeed: string;
  nonce: number;
  commitment: string;
  rtpBps: number;
  rows: number;
  columns: number;
  steps: number;
  moves: number[];
  revealed: number[][];
  board?: number[][];
  status: 'active' | 'lost' | 'cashed' | 'completed';
  payout: number;
  multiplier: number;
  won: boolean;
  createdAt: string;
};
export type Round = HiLoRound | LadderRound;
export type State = {
  balance: number;
  rtpBps: number;
  version: number;
  commitment: string;
  nonce: number;
  rounds: Round[];
  activeLadder: LadderRound | null;
  retired: { seed: string; commitment: string; bets: number }[];
  audit: { from: number; to: number; at: string; version: number }[];
  stats: { count: number; wagered: number; paid: number };
};
